name: iot_device
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.0.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  fl_chart: ^0.65.0
  intl: ^0.18.1  # <-- Add this line
  provider: ^6.1.5
  flutter_blue_plus: 
  http: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/icons/
    - assets/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: HachiMaruPop
      fonts:
        - asset: assets/fonts/HachiMaruPop-Regular.ttf
